GOOGLE_OAUTH_SCOPES: profile email openid
GOOGLE_OAUTH_CLIENT_ID: 811816529358-abktojt2gij8kla6auah5qk5m9vgl7p3.apps.googleusercontent.com
GOOGLE_OAUTH_CLIENT_SECRET: IpCid-PodUKb56EmCOaBHY-K
GOOGLE_OAUTH_REDIRECT_URI: http://localhost:8080/account/google-login/redirect
MONGO_CONNECTION_STRING: mongodb+srv://mongodbroot:s3curedp%40s%24w0rd89@mongowork.sxfuk.mongodb.net/?retryWrites=true&w=majority
DATABASE: timelyship-dev-db

FB_OAUTH_SCOPES: email
FB_OAUTH_CLIENT_ID: 893056244431932
FB_OAUTH_CLIENT_SECRET: 3ff6ee70e776264b1733a97b45b23cb7
FB_OAUTH_REDIRECT_URI: http://localhost:8080/account/fb-login/redirect
EMAIL_VERIFICATION_QUEUE: https://sqs.ap-southeast-1.amazonaws.com/135129372575/MY_FIRST_STD_QUEUE
ACCESS_SECRET: BKwxuR9sJwCsTbJmZWfOWFRHSX6VW5kMvGFQPCtwqztkdEWqMoVvjgHf4TLxcx69Z2IFJZFpHGsCdeboGCUM1JZKz15FJgX4bAFSlHMIi0FTvQhQX3a7lsuXy6uQBSwO
REFRESH_SECRET: 96tJqizuYSCwTbiUAt0wgMxhDyO0zO45d1wTNklbT4L4RrOQwoNsu6nU68LpfeC0tfxyAVSvULmD7RJaeT7kPFMCndVZZ3293c26ekjKXyqNn8u5FO6RSH7ZS40Ef1il
TOKEN_ISSUER: timelyship.com
ACCESS_TOKEN_EXP_MINUTE: 1440
REFRESH_TOKEN_EXP_MINUTE: 10080
LOGGER_OUTPUT_PATH: stdout
S3_BUCKET_PROFILE_PICTURE: timelyship.com-profile-dev
PUBLISH_EMAIL_VERIFICATION_MSG_TO_SQS: true