GOOGLE_OAUTH_SCOPES: profile email openid
GOOGLE_OAUTH_CLIENT_ID: 811816529358-abktojt2gij8kla6auah5qk5m9vgl7p3.apps.googleusercontent.com
GOOGLE_OAUTH_CLIENT_SECRET: IpCid-PodUKb56EmCOaBHY-K
GOOGLE_OAUTH_REDIRECT_URI: http://localhost:8080/account/google-login/redirect
MONGO_CONNECTION_STRING: mongodb+srv://mongodbroot:s3curedp%40s%24w0rd89@mongowork.sxfuk.mongodb.net/?retryWrites=true&w=majority
DATABASE: timelyship-dev-db