// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package appwiring

import (
	"go.uber.org/zap"
	"timelyship.com/accounts/repository"
	"timelyship.com/accounts/service"
)

// Injectors from wire.go:

func InitAccountService(logger zap.Logger) service.AccountService {
	accountRepository := repository.ProvideAccountRepository(logger)
	accountService := service.ProvideAccountService(accountRepository, logger)
	return accountService
}
